# -*- coding: utf-8 -*-
"""2502190005_lab07

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZjeZuVvGK1eZmWN3ZNkS8_rPLJXuTm74
"""

#JOB-A
def parse_line(line):
    """Take one raw line and return code, family and diameter."""
    code, dia = line.split(",")
    code = code.strip().upper()
    family = code.split("-")[1]
    return code, family, float(dia)
class Shaft:
    """Represent a shaft and its inspection results."""

    def __init__(self, code, dia):
        self.code = code
        self.dia = dia

    def deviation(self):
        """Return deviation from the target diameter of 25.00 mm."""
        return self.dia - 25.00

    def verdict(self):
        """Return ACCEPT, OVERSIZE or UNDERSIZE."""
        if self.dia > 25.05:
            return "OVERSIZE"
        elif self.dia < 24.95:
            return "UNDERSIZE"
        else:
            return "ACCEPT"
s1 = Shaft("TEST-001", 25.00)
s2 = Shaft("TEST-002", 25.08)
s3 = Shaft("TEST-003", 24.90)

print(s1.code, s1.verdict(), f"{s1.deviation():.2f}")
print(s2.code, s2.verdict(), f"{s2.deviation():.2f}")
print(s3.code, s3.verdict(), f"{s3.deviation():.2f}")

#JOB-B
raw_lines = [
    "MS-FLG-2026-0041, 24.98",
    " ms-flg-2026-0042, 25.01 ",
    "AL-BRK-2026-0007, 24.95",
    "MS-FLG-2026-0043, 25.04",
    "AL-BRK-2026-0008, 25.12",
    "ms-shf-2026-0101, 24.88",
    "MS-FLG-2026-0044, 24.99",
    "AL-BRK-2026-0009, 25.02",
    "MS-SHF-2026-0102, 25.07",
    "MS-FLG-2026-0045, 24.93"
]
parts = []

for line in raw_lines:
    code, family, dia = parse_line(line)
    parts.append(Shaft(code, dia))
for p in parts:
    print(p.code, p.verdict(), f"{p.deviation():.2f}")
counts = {
    "ACCEPT": 0,
    "OVERSIZE": 0,
    "UNDERSIZE": 0
}

for p in parts:
    counts[p.verdict()] += 1

print(counts)
ranked = sorted(
    parts,
    key=lambda p: abs(p.deviation()),
    reverse=True
)
print("THREE WORST PARTS")

for p in ranked[:3]:
    print(p.code, p.verdict(), f"{p.deviation():.2f} mm")

#JOB-C
class Batch:
    """Represent a batch containing multiple Shaft objects."""

    def __init__(self, batch_no):
        self.batch_no = batch_no
        self.parts = []

    def add(self, part):
        """Add a Shaft object to the batch."""
        self.parts.append(part)

    def acceptance_pct(self):
        """Return the percentage of accepted parts."""
        if len(self.parts) == 0:
            return 0

        accepted = 0

        for part in self.parts:
            if part.verdict() == "ACCEPT":
                accepted += 1

        return (accepted / len(self.parts)) * 100

    def worst(self):
        """Return the part object with the largest absolute deviation."""
        if len(self.parts) == 0:
            return None

        return max(self.parts, key=lambda p: abs(p.deviation()))
b = Batch("BATCH-07")

for p in parts:
    b.add(p)
worst_part = b.worst()

print(
    f"Batch {b.batch_no} | "
    f"Parts={len(b.parts)} | "
    f"Acceptance={b.acceptance_pct():.2f}% | "
    f"Worst={worst_part.code}"
)
print(b.worst().code)
print(b.worst().verdict())
print(f"{b.worst().deviation():.2f} mm")